This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./Experimental_Report.ist...
** Input style error (file = ./Experimental_Report.ist, line = 5):
   -- Unknown specifier item_x.
...done (6 attributes redefined, 1 ignored).
Scanning input file Experimental_Report.acn...done (0 entries accepted, 0 rejected).
Nothing written in Experimental_Report.acr.
Transcript written in Experimental_Report.alg.
